### ISSUE TITLE
info needed

### ISSUE THREAD

**Issue by usergoodvery** [MogiePete/zabbix-galera-template#1]
hi
thanks for sharing this. I am relatively new to zabbix, but I am not sure if the installation info provided is complete. The instructions on the server suggests: "Add Value Mapping Information", but you seem to do that already in the template. What else needs to be done?

Also, where do I specify mysql's instance ip and port? (if not using standard port/localhost)

Finally, for the zabbix mysql account, where do I specify username/password? or just create ~/.my.cnf file with that info in it for the zabbix unix user?

regards,

ayman

**Comment by MogiePete** [comment]
I always add the Value Mapping prior to importing a template. 

If you are not using the default port you would need to modify the userparameter_galera.conf to specify the port.

ex: HOME=/var/lib/zabbix mysql -N -P <port_number>

Under client in my.cnf or server.cnf (depending on what version you run) you need to specify the user and password as such.

[client]
user = <user_name>
password = <user_pass>

**Comment by usergoodvery** [comment]
Thanks. I am still not clear on what value mapping is needed for. None of the templates I installed in the past required fiddling with value maps, as that's normally already provided in the template.

Are you referring to this section of the template or something else?
<value_maps>
        <value_map>
            <name>Galera State</name>
            <mappings>
                <mapping>
                    <value>1</value>
                    <newvalue>Joining</newvalue>
                </mapping>
                <mapping>
                    <value>2</value>
                    <newvalue>Donor/Desynced</newvalue>
                </mapping>
                <mapping>
                    <value>3</value>
                    <newvalue>Joined</newvalue>
                </mapping>
                <mapping>
                    <value>4</value>
                    <newvalue>Synced</newvalue>
                </mapping>
            </mappings>
        </value_map>
    </value_maps>

**Comment by MogiePete** [comment]
The instructions can be found in Zabbix's documentation for adding Value Mapping.

https://www.zabbix.com/documentation/3.2/manual/config/items/mapping

**Comment by usergoodvery** [comment]
OK I see what you mean that gives it an extra polish, but otherwise it's optional really
