### ISSUE TITLE
Mysql 5.7.6 or later deprecates use of information_schema.GLOBAL_STATUS

### ISSUE THREAD

**Issue by anthonysomerset** [MogiePete/zabbix-galera-template#4]
more info here: https://dev.mysql.com/doc/refman/5.7/en/performance-schema-variable-table-migration.html

there are 2 ways to solve this...

Enable `show_compatibility_56` variable in mysql but this breaks in MySQL 8.x permanently

update all references in the user parameter file from `information_schema.GLOBAL_STATUS` to `performance_schema.global_status`

the latter appears to work just fine in current 5.7.x releases

**Comment by MogiePete** [comment]
I do not have a Galera system to test that utilizes MySQL 8.x so I am marking this as won't fix.
